version: '3'

volumes:
  postgres_data:
    driver: local

services:
  nats:
    container_name: nats
    image: nats:latest
    ports:
      - 4222:4222

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017

  mongo_seed:
    container_name: mongo_seed
    build: ./mongo-seed
    depends_on:
      - mongodb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  bitloops-rest:
    build: ./bitloops-rest
    container_name: bitloops-rest
    image: bitloops/bitloops-rest:latest
    env_file:
      - bitloops-rest/docker.env
    ports:
      - 3005:3005
    depends_on:
      - nats
      - mongodb
      - redis

  bitloops-engine:
    build: ./bitloops-engine
    container_name: bitloops-engine
    image: bitloops/bitloops-engine:latest
    env_file:
      - bitloops-engine/docker.env
    ports:
      - 8081:8080
    depends_on:
      - nats
      - mongodb
      - redis

  csrv-mongo:
    container_name: csrv-mongo
    image: bitloops/csrv-mongo:v0.1.2
    ports:
      - 4000:4000
    environment:
      - SERVICE_PORT=4000
      - MONGO_URL_PREFIX=mongodb://
      - MONGO_URL_SUFFIX=mongodb:27017
    depends_on:
      - mongodb

  csrv-redis:
    container_name: csrv-redis
    image: bitloops/csrv-redis:v0.0.8
    ports:
      - 8085:8085
    environment:
      - PORT=8085
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
