use serde::{Deserialize, Serialize};

pub const NAVIGATION_CONTEXT_CAPABILITY_ID: &str = "navigation_context";
pub const NAVIGATION_CONTEXT_CONSUMER_ID: &str = "navigation_context.snapshot";

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum NavigationPrimitiveKind {
    FileBlob,
    Package,
    Module,
    Symbol,
    DependencyEdge,
    CallEdge,
    DataFlowEdge,
    Entrypoint,
    PublicContract,
    DataObject,
    ConfigKey,
    RuntimeFlow,
    TestCase,
    VerificationCommand,
    PipelineJob,
    DecisionRecord,
    OwnershipRule,
    MetricObservation,
    IntegrationContract,
    SecurityBoundary,
    GlossaryTerm,
}

impl NavigationPrimitiveKind {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::FileBlob => "FILE_BLOB",
            Self::Package => "PACKAGE",
            Self::Module => "MODULE",
            Self::Symbol => "SYMBOL",
            Self::DependencyEdge => "DEPENDENCY_EDGE",
            Self::CallEdge => "CALL_EDGE",
            Self::DataFlowEdge => "DATA_FLOW_EDGE",
            Self::Entrypoint => "ENTRYPOINT",
            Self::PublicContract => "PUBLIC_CONTRACT",
            Self::DataObject => "DATA_OBJECT",
            Self::ConfigKey => "CONFIG_KEY",
            Self::RuntimeFlow => "RUNTIME_FLOW",
            Self::TestCase => "TEST_CASE",
            Self::VerificationCommand => "VERIFICATION_COMMAND",
            Self::PipelineJob => "PIPELINE_JOB",
            Self::DecisionRecord => "DECISION_RECORD",
            Self::OwnershipRule => "OWNERSHIP_RULE",
            Self::MetricObservation => "METRIC_OBSERVATION",
            Self::IntegrationContract => "INTEGRATION_CONTRACT",
            Self::SecurityBoundary => "SECURITY_BOUNDARY",
            Self::GlossaryTerm => "GLOSSARY_TERM",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationViewDefinition {
    pub view_id: &'static str,
    pub view_kind: &'static str,
    pub label: &'static str,
    pub query_version: &'static str,
    pub primitive_kinds: &'static [NavigationPrimitiveKind],
}

pub static NAVIGATION_VIEW_DEFINITIONS: &[NavigationViewDefinition] = &[
    NavigationViewDefinition {
        view_id: "product_domain_overview",
        view_kind: "PRODUCT_DOMAIN_OVERVIEW",
        label: "Product/domain overview",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::GlossaryTerm,
            NavigationPrimitiveKind::Entrypoint,
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::DecisionRecord,
            NavigationPrimitiveKind::Module,
        ],
    },
    NavigationViewDefinition {
        view_id: "architecture_map",
        view_kind: "ARCHITECTURE_MAP",
        label: "Architecture map",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::Package,
            NavigationPrimitiveKind::Module,
            NavigationPrimitiveKind::DependencyEdge,
            NavigationPrimitiveKind::CallEdge,
            NavigationPrimitiveKind::RuntimeFlow,
            NavigationPrimitiveKind::DataObject,
            NavigationPrimitiveKind::IntegrationContract,
            NavigationPrimitiveKind::Entrypoint,
            NavigationPrimitiveKind::Symbol,
        ],
    },
    NavigationViewDefinition {
        view_id: "entry_points",
        view_kind: "ENTRY_POINTS",
        label: "Entry points",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::Entrypoint,
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::SecurityBoundary,
            NavigationPrimitiveKind::Package,
        ],
    },
    NavigationViewDefinition {
        view_id: "change_playbooks",
        view_kind: "CHANGE_PLAYBOOKS",
        label: "Change playbooks",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::Module,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::TestCase,
            NavigationPrimitiveKind::VerificationCommand,
            NavigationPrimitiveKind::DecisionRecord,
            NavigationPrimitiveKind::MetricObservation,
        ],
    },
    NavigationViewDefinition {
        view_id: "dependency_graph",
        view_kind: "DEPENDENCY_GRAPH",
        label: "Dependency graph",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::Package,
            NavigationPrimitiveKind::Module,
            NavigationPrimitiveKind::DependencyEdge,
            NavigationPrimitiveKind::CallEdge,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::FileBlob,
        ],
    },
    NavigationViewDefinition {
        view_id: "data_model",
        view_kind: "DATA_MODEL",
        label: "Data model",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::DataObject,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::DataFlowEdge,
            NavigationPrimitiveKind::ConfigKey,
        ],
    },
    NavigationViewDefinition {
        view_id: "runtime_flows",
        view_kind: "RUNTIME_FLOWS",
        label: "Runtime flows",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::RuntimeFlow,
            NavigationPrimitiveKind::Entrypoint,
            NavigationPrimitiveKind::CallEdge,
            NavigationPrimitiveKind::DataFlowEdge,
            NavigationPrimitiveKind::DataObject,
            NavigationPrimitiveKind::PipelineJob,
        ],
    },
    NavigationViewDefinition {
        view_id: "test_map",
        view_kind: "TEST_MAP",
        label: "Test map",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::TestCase,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::Entrypoint,
            NavigationPrimitiveKind::VerificationCommand,
            NavigationPrimitiveKind::MetricObservation,
        ],
    },
    NavigationViewDefinition {
        view_id: "build_release_deploy",
        view_kind: "BUILD_RELEASE_DEPLOY",
        label: "Build/release/deploy",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::PipelineJob,
            NavigationPrimitiveKind::VerificationCommand,
            NavigationPrimitiveKind::Package,
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::IntegrationContract,
        ],
    },
    NavigationViewDefinition {
        view_id: "configuration",
        view_kind: "CONFIGURATION",
        label: "Configuration",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::DataObject,
            NavigationPrimitiveKind::SecurityBoundary,
        ],
    },
    NavigationViewDefinition {
        view_id: "ownership_and_churn",
        view_kind: "OWNERSHIP_AND_CHURN",
        label: "Ownership and churn",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::OwnershipRule,
            NavigationPrimitiveKind::MetricObservation,
            NavigationPrimitiveKind::FileBlob,
            NavigationPrimitiveKind::Module,
            NavigationPrimitiveKind::Package,
        ],
    },
    NavigationViewDefinition {
        view_id: "architectural_decisions",
        view_kind: "ARCHITECTURAL_DECISIONS",
        label: "Architectural decisions",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::DecisionRecord,
            NavigationPrimitiveKind::Module,
            NavigationPrimitiveKind::DependencyEdge,
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::DataObject,
        ],
    },
    NavigationViewDefinition {
        view_id: "naming_conventions",
        view_kind: "NAMING_CONVENTIONS",
        label: "Naming conventions",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::GlossaryTerm,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::Module,
            NavigationPrimitiveKind::PublicContract,
        ],
    },
    NavigationViewDefinition {
        view_id: "generated_metrics",
        view_kind: "GENERATED_METRICS",
        label: "Generated metrics",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::MetricObservation,
            NavigationPrimitiveKind::FileBlob,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::DependencyEdge,
            NavigationPrimitiveKind::TestCase,
        ],
    },
    NavigationViewDefinition {
        view_id: "public_api_surface",
        view_kind: "PUBLIC_API_SURFACE",
        label: "Public API surface",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::Entrypoint,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::IntegrationContract,
        ],
    },
    NavigationViewDefinition {
        view_id: "error_and_failure_modes",
        view_kind: "ERROR_AND_FAILURE_MODES",
        label: "Error and failure modes",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::RuntimeFlow,
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::MetricObservation,
        ],
    },
    NavigationViewDefinition {
        view_id: "external_integrations",
        view_kind: "EXTERNAL_INTEGRATIONS",
        label: "External integrations",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::IntegrationContract,
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::SecurityBoundary,
            NavigationPrimitiveKind::RuntimeFlow,
            NavigationPrimitiveKind::TestCase,
        ],
    },
    NavigationViewDefinition {
        view_id: "local_development_setup",
        view_kind: "LOCAL_DEVELOPMENT_SETUP",
        label: "Local development setup",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::VerificationCommand,
            NavigationPrimitiveKind::Package,
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::PipelineJob,
            NavigationPrimitiveKind::IntegrationContract,
        ],
    },
    NavigationViewDefinition {
        view_id: "security_privacy_model",
        view_kind: "SECURITY_PRIVACY_MODEL",
        label: "Security/privacy model",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::SecurityBoundary,
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::DataObject,
            NavigationPrimitiveKind::IntegrationContract,
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::RuntimeFlow,
        ],
    },
    NavigationViewDefinition {
        view_id: "glossary_ontology",
        view_kind: "GLOSSARY_ONTOLOGY",
        label: "Glossary/ontology",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::GlossaryTerm,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::Module,
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::DecisionRecord,
        ],
    },
    NavigationViewDefinition {
        view_id: "agent_context_bundle",
        view_kind: "AGENT_CONTEXT_BUNDLE",
        label: "Agent context bundle",
        query_version: "1",
        primitive_kinds: &[
            NavigationPrimitiveKind::FileBlob,
            NavigationPrimitiveKind::Package,
            NavigationPrimitiveKind::Module,
            NavigationPrimitiveKind::Symbol,
            NavigationPrimitiveKind::DependencyEdge,
            NavigationPrimitiveKind::CallEdge,
            NavigationPrimitiveKind::DataFlowEdge,
            NavigationPrimitiveKind::Entrypoint,
            NavigationPrimitiveKind::PublicContract,
            NavigationPrimitiveKind::DataObject,
            NavigationPrimitiveKind::ConfigKey,
            NavigationPrimitiveKind::RuntimeFlow,
            NavigationPrimitiveKind::TestCase,
            NavigationPrimitiveKind::VerificationCommand,
            NavigationPrimitiveKind::PipelineJob,
            NavigationPrimitiveKind::DecisionRecord,
            NavigationPrimitiveKind::OwnershipRule,
            NavigationPrimitiveKind::MetricObservation,
            NavigationPrimitiveKind::IntegrationContract,
            NavigationPrimitiveKind::SecurityBoundary,
            NavigationPrimitiveKind::GlossaryTerm,
        ],
    },
];
