use std::path::{Path, PathBuf};

use anyhow::{Result, anyhow};
use serde_json::to_string;

use super::plugin::{
    BITLOOPS_CMD_PLACEHOLDER, BOOTSTRAP_CONTEXT_PLACEHOLDER, PLUGIN_TEMPLATE,
    session_bootstrap_text,
};

pub const PLUGIN_FILE_NAME: &str = "bitloops.ts";
pub const PLUGIN_DIR_NAME: &str = "plugins";
pub const BITLOOPS_MARKER: &str = "Auto-generated by `bitloops init --agent opencode`";

pub fn get_plugin_path(repo_root: &Path) -> PathBuf {
    repo_root
        .join(".opencode")
        .join(PLUGIN_DIR_NAME)
        .join(PLUGIN_FILE_NAME)
}

pub fn render_plugin_template(repo_root: &Path, local_dev: bool) -> Result<String> {
    if !PLUGIN_TEMPLATE.contains(BITLOOPS_CMD_PLACEHOLDER) {
        return Err(anyhow!(
            "plugin template missing BITLOOPS command placeholder"
        ));
    }
    if !PLUGIN_TEMPLATE.contains(BOOTSTRAP_CONTEXT_PLACEHOLDER) {
        return Err(anyhow!(
            "plugin template missing bootstrap context placeholder"
        ));
    }
    let bitloops_cmd = if local_dev {
        "cargo run --"
    } else {
        "bitloops"
    };

    let bootstrap_context = to_string(&session_bootstrap_text(repo_root))
        .map_err(|err| anyhow!("failed to serialize bootstrap context: {err}"))?;

    Ok(PLUGIN_TEMPLATE
        .replace(BITLOOPS_CMD_PLACEHOLDER, bitloops_cmd)
        .replace(BOOTSTRAP_CONTEXT_PLACEHOLDER, &bootstrap_context))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapters::agents::open_code::skills::{
        OPEN_CODE_SKILL_RELATIVE_PATH, install_repo_skill,
    };

    struct RenderedMessage {
        role: String,
        parts: Vec<String>,
    }

    fn write_repo_policy(dir: &tempfile::TempDir, body: &str) {
        std::fs::write(dir.path().join(".bitloops.toml"), body).expect("write repo policy");
    }

    fn rendered_message(_id: &str, role: &str, parts: &[&str]) -> RenderedMessage {
        RenderedMessage {
            role: role.to_string(),
            parts: parts.iter().map(|part| part.to_string()).collect(),
        }
    }

    fn rendered_const(rendered: &str, name: &str) -> String {
        let prefix = format!("const {name} = ");
        let line = rendered
            .lines()
            .find_map(|line| line.trim_start().strip_prefix(&prefix))
            .unwrap_or_else(|| panic!("rendered plugin should contain {name}"));

        serde_json::from_str(line).unwrap_or_else(|err| panic!("failed to parse {name}: {err}"))
    }

    fn count_parts_containing(message: &RenderedMessage, marker: &str) -> usize {
        message
            .parts
            .iter()
            .filter(|part| part.contains(marker))
            .count()
    }

    fn has_text_part_containing(message: &RenderedMessage, marker: &str) -> bool {
        count_parts_containing(message, marker) > 0
    }

    fn apply_rendered_transform(rendered: &str, messages: &mut [RenderedMessage]) {
        let bootstrap_context = rendered_const(rendered, "BOOTSTRAP_CONTEXT");
        if bootstrap_context.is_empty() {
            return;
        }

        if !bootstrap_context.is_empty()
            && let Some(first_user) = messages
                .iter_mut()
                .find(|message| message.role == "user" && !message.parts.is_empty())
            && !has_text_part_containing(first_user, "EXTREMELY_IMPORTANT")
        {
            first_user.parts.insert(0, bootstrap_context);
        }
    }

    #[test]
    fn render_plugin_template_injects_capability_aware_bootstrap_when_skill_exists() {
        let dir = tempfile::tempdir().expect("tempdir");
        let repo_root = dir.path();
        write_repo_policy(
            &dir,
            r#"
[capture]
enabled = true
"#,
        );
        install_repo_skill(repo_root).expect("install skill");

        let rendered = render_plugin_template(repo_root, false).expect("render should succeed");

        assert!(rendered.contains(r#"const BITLOOPS_CMD = "bitloops""#));
        assert!(
            rendered.contains(OPEN_CODE_SKILL_RELATIVE_PATH),
            "bootstrap text should reference the repo-local skill path"
        );
        assert!(
            rendered.contains("DevQL-capable guidance surface"),
            "bootstrap text should preserve the capability-aware guidance"
        );
        assert!(
            rendered.contains("When DevQL is available in this session"),
            "bootstrap text should prefer DevQL conditionally"
        );
        assert!(
            rendered.contains("fall back to targeted repo search or file reads"),
            "bootstrap text should preserve the fallback guidance"
        );
        assert!(
            !rendered.contains("bitloops devql query"),
            "bootstrap text should not inline DevQL query suggestions"
        );
        assert!(
            !rendered.contains("name: devql-explore-first"),
            "bootstrap text should not inline the managed skill body"
        );
        assert!(
            rendered.contains("<EXTREMELY_IMPORTANT>"),
            "plugin should inject bootstrap context through OpenCode's messages transform"
        );
        assert!(
            rendered.contains("\"experimental.chat.messages.transform\": async"),
            "plugin should inject bootstrap context through OpenCode's messages transform"
        );
        assert!(
            rendered.contains("config.skills.paths.push(repoSkillsDir)"),
            "plugin should register the repo-local .opencode/skills directory"
        );
        assert!(
            rendered.contains("await Bun.file(repoSkillPath).exists()"),
            "plugin should re-check skill presence before injecting bootstrap text"
        );
        assert!(!rendered.contains("const TURN_GUIDANCE_CONTEXT"));
        assert!(!rendered.contains("const latestUserPromptByMessageID"));
        assert!(!rendered.contains("let latestUserMessageID"));
        assert!(!rendered.contains("\"chat.message\": async"));
        assert!(!rendered.contains("promptWarrantsDevql(prompt)"));
        assert!(!rendered.contains("function promptWarrantsDevql"));
        assert!(!rendered.contains("TURN_GUIDANCE_CONTEXT"));
        assert!(!rendered.contains("latestUser.parts.unshift"));
        assert!(!rendered.contains("const DEVQL_REPO_UNDERSTANDING_TERMS"));
        assert!(!rendered.contains("const DEVQL_EXECUTION_TERMS"));
        assert!(!rendered.contains("const DEVQL_CODE_REFERENCE_MARKERS"));
        assert!(!rendered.contains("\"experimental.chat.system.transform\""));
    }

    #[test]
    fn render_plugin_template_preserves_model_metadata_for_transcripts() {
        let dir = tempfile::tempdir().expect("tempdir");
        let rendered = render_plugin_template(dir.path(), false).expect("render should succeed");

        assert!(
            rendered.contains("extractModelMetadata"),
            "plugin should centralize model metadata preservation"
        );
        assert!(
            rendered.contains("modelID"),
            "plugin should preserve OpenCode's uppercase modelID field"
        );
        assert!(
            rendered.contains("providerID"),
            "plugin should preserve OpenCode's uppercase providerID field"
        );
    }

    #[test]
    fn render_plugin_template_omits_turn_guidance_prompt_heuristic_machinery() {
        let dir = tempfile::tempdir().expect("tempdir");
        let rendered = render_plugin_template(dir.path(), false).expect("render should succeed");

        assert!(!rendered.contains("function promptWarrantsDevql"));
        assert!(!rendered.contains("DEVQL_REPO_UNDERSTANDING_TERMS"));
        assert!(!rendered.contains("DEVQL_EXECUTION_TERMS"));
        assert!(!rendered.contains("DEVQL_CODE_REFERENCE_MARKERS"));
    }

    #[test]
    fn render_plugin_template_stays_quiet_when_policy_disables_guidance() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_repo_policy(
            &dir,
            r#"
[agents]
supported = ["opencode"]
devql_guidance_enabled = false
"#,
        );
        install_repo_skill(dir.path()).expect("install skill");

        let rendered = render_plugin_template(dir.path(), false).expect("render should succeed");

        assert!(rendered.contains(r#"const BITLOOPS_CMD = "bitloops""#));
        assert_eq!(rendered_const(&rendered, "BOOTSTRAP_CONTEXT"), "");
        assert!(!rendered.contains(OPEN_CODE_SKILL_RELATIVE_PATH));
        assert!(!rendered.contains("DevQL-capable guidance surface"));
        assert!(!rendered.contains("<EXTREMELY_IMPORTANT>"));
    }

    #[test]
    fn render_plugin_template_switches_to_local_dev_command() {
        let dir = tempfile::tempdir().expect("tempdir");
        let rendered = render_plugin_template(dir.path(), true).expect("render should succeed");

        assert!(rendered.contains(r#"const BITLOOPS_CMD = "cargo run --""#));
    }

    #[test]
    fn render_plugin_template_transform_injects_bootstrap_only_by_message_role() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_repo_policy(
            &dir,
            r#"
[capture]
enabled = true
"#,
        );
        install_repo_skill(dir.path()).expect("install skill");
        let rendered = render_plugin_template(dir.path(), false).expect("render should succeed");

        let mut messages = vec![
            rendered_message("first-user", "user", &["Initial request"]),
            rendered_message("assistant", "assistant", &["Assistant response"]),
            rendered_message(
                "latest-user",
                "user",
                &["Explain src/adapters/agents/open_code/plugin.rs"],
            ),
        ];

        apply_rendered_transform(&rendered, &mut messages);
        apply_rendered_transform(&rendered, &mut messages);

        assert_eq!(
            count_parts_containing(&messages[0], "EXTREMELY_IMPORTANT"),
            1
        );
        assert_eq!(
            messages[2].parts,
            vec!["Explain src/adapters/agents/open_code/plugin.rs"]
        );
        assert_eq!(
            count_parts_containing(&messages[1], "EXTREMELY_IMPORTANT"),
            0
        );
    }

    #[test]
    fn render_plugin_template_transform_does_not_append_guidance_to_later_prompts() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_repo_policy(
            &dir,
            r#"
[capture]
enabled = true
"#,
        );
        install_repo_skill(dir.path()).expect("install skill");
        let rendered = render_plugin_template(dir.path(), false).expect("render should succeed");

        let mut messages = vec![
            rendered_message("first-user", "user", &["Initial request"]),
            rendered_message("latest-user", "user", &["Explain src/lib.rs"]),
        ];

        apply_rendered_transform(&rendered, &mut messages);

        assert_eq!(
            count_parts_containing(&messages[0], "EXTREMELY_IMPORTANT"),
            1
        );
        assert_eq!(messages[1].parts, vec!["Explain src/lib.rs"]);
    }

    #[test]
    fn render_plugin_template_transform_disabled_guidance_injects_nothing() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_repo_policy(
            &dir,
            r#"
[agents]
supported = ["opencode"]
devql_guidance_enabled = false
"#,
        );
        install_repo_skill(dir.path()).expect("install skill");
        let rendered = render_plugin_template(dir.path(), false).expect("render should succeed");
        assert_eq!(rendered_const(&rendered, "BOOTSTRAP_CONTEXT"), "");

        let mut messages = vec![
            rendered_message("first-user", "user", &["Initial request"]),
            rendered_message("latest-user", "user", &["Explain src/lib.rs"]),
        ];

        apply_rendered_transform(&rendered, &mut messages);

        assert_eq!(messages[0].parts, vec!["Initial request"]);
        assert_eq!(messages[1].parts, vec!["Explain src/lib.rs"]);
    }
}
