use std::path::Path;

pub const BITLOOPS_CMD_PLACEHOLDER: &str = "__BITLOOPS_CMD__";
pub const BOOTSTRAP_CONTEXT_PLACEHOLDER: &str = "__BOOTSTRAP_CONTEXT__";

pub(crate) fn session_bootstrap_text(_repo_root: &Path) -> String {
    String::new()
}

pub const PLUGIN_TEMPLATE: &str = r##"// Bitloops CLI plugin for OpenCode
// Auto-generated by `bitloops init --agent opencode`
// Do not edit manually - changes will be overwritten on next install.
// Requires Bun runtime (used by OpenCode's plugin system for loading ESM plugins).
import type { Plugin } from "@opencode-ai/plugin"
import { tmpdir } from "node:os"
import path from "node:path"

export const BitloopsPlugin: Plugin = async ({ client, directory, $ }) => {
  const BITLOOPS_CMD = __BITLOOPS_CMD__
  const BOOTSTRAP_CONTEXT = __BOOTSTRAP_CONTEXT__
  // Store transcripts in a temp directory - these are ephemeral handoff files
  // between the plugin and the hook handler. Once checkpointed, the data
  // lives on git refs and the file is disposable.
  const sanitized = directory.replace(/[^a-zA-Z0-9]/g, "-")
  const transcriptDir = `${tmpdir()}/bitloops-opencode/${sanitized}`
  const seenUserMessages = new Set<string>()

  // In-memory stores - used to write transcripts without relying on the SDK API,
  // which may be unavailable during shutdown.
  // messageStore: keyed by message ID, stores message metadata (role, time, tokens, etc.)
  const messageStore = new Map<string, any>()
  // partStore: keyed by message ID, stores accumulated parts from message.part.updated events
  const partStore = new Map<string, any[]>()
  let currentSessionID: string | null = null
  // Full session info from session.created - needed for OpenCode export format on resume/rewind
  let currentSessionInfo: any = null

  // Ensure transcript directory exists
  await $`mkdir -p ${transcriptDir}`.quiet().nothrow()

  /**
   * Pipe JSON payload to an bitloops hooks command.
   * Errors are logged but never thrown - plugin failures must not crash OpenCode.
   */
  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const proc = Bun.spawn([...BITLOOPS_CMD, "hooks", "opencode", hookName], {
        cwd: directory,
        stdin: new TextEncoder().encode(json + "\n"),
        stdout: "ignore",
        stderr: "ignore",
      })
      await proc.exited
    } catch {
      // Silently ignore - plugin failures must not crash OpenCode
    }
  }

  /**
   * Synchronous variant for hooks that fire near process exit (turn-end, session-end).
   * `session.status` idle can be followed immediately by process shutdown, so
   * blocking here avoids dropping the hook command before it reaches Bitloops.
   */
  function callHookSync(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      Bun.spawnSync([...BITLOOPS_CMD, "hooks", "opencode", hookName], {
        cwd: directory,
        stdin: new TextEncoder().encode(json + "\n"),
        stdout: "ignore",
        stderr: "ignore",
      })
    } catch {
      // Silently ignore - plugin failures must not crash OpenCode
    }
  }

  /** Extract text content from a list of parts. */
  function textFromParts(parts: any[]): string {
    return parts
      .filter((p: any) => p.type === "text")
      .map((p: any) => p.text ?? "")
      .join("\n")
  }

  /** Check whether a message already contains a text marker. */
  function hasTextPartContaining(message: any, marker: string): boolean {
    return (message.parts ?? []).some(
      (p: any) => p.type === "text" && typeof p.text === "string" && p.text.includes(marker)
    )
  }

  function firstNonEmptyString(...values: any[]): string | undefined {
    for (const value of values) {
      if (typeof value === "string" && value.trim()) {
        return value.trim()
      }
    }
  }

  function extractModelMetadata(...sources: any[]): Record<string, string> {
    let model: string | undefined
    let modelID: string | undefined
    let providerID: string | undefined

    for (const source of sources) {
      if (!source || typeof source !== "object") continue

      model = model ?? firstNonEmptyString(
        source.model,
        source.modelName,
        source.model_name,
        source.modelSlug,
        source.model_slug,
        source.modelId,
        source.modelID,
        source.model_id,
        source.model?.id,
        source.model?.modelID,
        source.model?.modelId,
        source.model?.model_id,
        source.model?.modelName,
        source.model?.model_name,
        source.model?.modelSlug,
        source.model?.model_slug,
      )
      modelID = modelID ?? firstNonEmptyString(
        source.modelID,
        source.modelId,
        source.model_id,
        source.model?.modelID,
        source.model?.modelId,
        source.model?.model_id,
        source.model?.id,
      )
      providerID = providerID ?? firstNonEmptyString(
        source.providerID,
        source.providerId,
        source.provider_id,
        source.model?.providerID,
        source.model?.providerId,
        source.model?.provider_id,
      )
    }

    const resolvedModel = model ?? modelID
    return {
      ...(resolvedModel ? { model: resolvedModel } : {}),
      ...(modelID ? { modelID } : {}),
      ...(providerID ? { providerID } : {}),
    }
  }

  function latestSessionModelMetadata(sessionID: string | null): Record<string, string> {
    const messages = Array.from(messageStore.values())
      .filter((msg: any) =>
        !sessionID || msg.sessionID === sessionID || (!msg.sessionID && currentSessionID === sessionID)
      )
      .sort((a, b) => (b.time?.created ?? 0) - (a.time?.created ?? 0))

    return extractModelMetadata(messages[0], currentSessionInfo)
  }

  function hookModelPayload(...sources: any[]): Record<string, string> {
    const modelMetadata = extractModelMetadata(...sources)
    return modelMetadata.model ? { model: modelMetadata.model } : {}
  }

  /** Format a message object from its accumulated parts. */
  function formatMessageFromStore(msg: any) {
    const parts = partStore.get(msg.id) ?? []
    const modelMetadata = extractModelMetadata(msg, currentSessionInfo)
    return {
      id: msg.id,
      role: msg.role,
      content: textFromParts(parts),
      time: msg.time,
      ...modelMetadata,
      ...(msg.role === "assistant" ? {
        tokens: msg.tokens,
        cost: msg.cost,
        parts: parts.map((p: any) => ({
          type: p.type,
          ...(p.type === "text" ? { text: p.text } : {}),
          ...(p.type === "tool" ? { tool: p.tool, callID: p.callID, state: p.state } : {}),
        })),
      } : {}),
    }
  }

  /** Format a message from an API response (which includes parts inline). */
  function formatMessageFromAPI(info: any, parts: any[]) {
    const modelMetadata = extractModelMetadata(info, currentSessionInfo)
    return {
      id: info.id,
      role: info.role,
      content: textFromParts(parts),
      time: info.time,
      ...modelMetadata,
      ...(info.role === "assistant" ? {
        tokens: info.tokens,
        cost: info.cost,
        parts: parts.map((p: any) => ({
          type: p.type,
          ...(p.type === "text" ? { text: p.text } : {}),
          ...(p.type === "tool" ? { tool: p.tool, callID: p.callID, state: p.state } : {}),
        })),
      } : {}),
    }
  }

  /**
   * Write transcript as JSONL (one message per line) from in-memory stores.
   * This does NOT call the SDK API, so it works even during shutdown.
   */
  async function writeTranscriptFromMemory(sessionID: string): Promise<string> {
    const transcriptPath = `${transcriptDir}/${sessionID}.jsonl`
    try {
      const messages = Array.from(messageStore.values())
        .sort((a, b) => (a.time?.created ?? 0) - (b.time?.created ?? 0))

      const lines = messages.map(msg => JSON.stringify(formatMessageFromStore(msg)))
      await Bun.write(transcriptPath, lines.join("\n") + "\n")
    } catch {
      // Silently ignore write failures
    }
    return transcriptPath
  }

  /**
   * Try to fetch messages via the SDK API (returns messages with parts inline)
   * and write transcript as JSONL. Falls back to in-memory stores if the API is unavailable.
   */
  async function writeTranscriptWithFallback(sessionID: string): Promise<string> {
    const transcriptPath = `${transcriptDir}/${sessionID}.jsonl`
    try {
      const response = await client.session.message.list({ path: { id: sessionID } })
      // API returns Array<{ info: Message, parts: Array<Part> }>
      const items = response.data ?? []

      const lines = items.map((item: any) =>
        JSON.stringify(formatMessageFromAPI(item.info, item.parts ?? []))
      )
      await Bun.write(transcriptPath, lines.join("\n") + "\n")
      return transcriptPath
    } catch {
      // API unavailable (likely shutting down) - fall back to in-memory stores
      return writeTranscriptFromMemory(sessionID)
    }
  }

  /**
   * Write session in OpenCode's native export format (JSON).
   * This file is used by `opencode import` during resume/rewind to restore
   * the session into OpenCode's SQLite database with the original session ID.
   */
  async function writeExportJSON(sessionID: string): Promise<string> {
    const exportPath = `${transcriptDir}/${sessionID}.export.json`
    try {
      const messages = Array.from(messageStore.values())
        .sort((a, b) => (a.time?.created ?? 0) - (b.time?.created ?? 0))

      const exportData = {
        info: currentSessionInfo ?? { id: sessionID },
        messages: messages.map(msg => ({
          info: msg,
          parts: (partStore.get(msg.id) ?? []),
        })),
      }
      await Bun.write(exportPath, JSON.stringify(exportData))
    } catch {
      // Silently ignore - plugin failures must not crash OpenCode
    }
    return exportPath
  }

  return {
    config: async (config) => {
      config.skills = config.skills || {}
      config.skills.paths = config.skills.paths || []
      const repoSkillsDir = path.join(directory, ".opencode", "skills")
      if (!config.skills.paths.includes(repoSkillsDir)) {
        config.skills.paths.push(repoSkillsDir)
      }
    },

    "experimental.chat.messages.transform": async (_input, output) => {
      if (!BOOTSTRAP_CONTEXT) return
      const repoSkillPath = path.join(directory, ".opencode", "skills", "bitloops", "devql-explore-first", "SKILL.md")
      if (!(await Bun.file(repoSkillPath).exists())) return
      if (!output.messages.length) return

      if (BOOTSTRAP_CONTEXT) {
        const firstUser = output.messages.find((m: any) => m.info?.role === "user")
        if (firstUser?.parts?.length && !hasTextPartContaining(firstUser, "EXTREMELY_IMPORTANT")) {
          const ref = firstUser.parts[0]
          firstUser.parts.unshift({ ...ref, type: "text", text: BOOTSTRAP_CONTEXT })
        }
      }
    },

    event: async ({ event }) => {
      switch (event.type) {
        case "session.created": {
          const session = (event as any).properties?.info
          if (!session?.id) break
          currentSessionID = session.id
          currentSessionInfo = session
          await callHook("session-start", {
            session_id: session.id,
            transcript_path: `${transcriptDir}/${session.id}.jsonl`,
            ...hookModelPayload(session),
          })
          break
        }

        case "message.updated": {
          const msg = (event as any).properties?.info
          if (!msg) break
          // Store message metadata (role, time, tokens, etc.)
          // Content is NOT on the message - it arrives via message.part.updated events.
          messageStore.set(msg.id, msg)
          break
        }

        case "message.part.updated": {
          const part = (event as any).properties?.part
          if (!part?.messageID) break

          // Accumulate parts per message
          const existing = partStore.get(part.messageID) ?? []
          // Replace existing part with same id, or append new one
          const idx = existing.findIndex((p: any) => p.id === part.id)
          if (idx >= 0) {
            existing[idx] = part
          } else {
            existing.push(part)
          }
          partStore.set(part.messageID, existing)

          // Fire turn-start on the first text part of a new user message
          const msg = messageStore.get(part.messageID)
          if (msg?.role === "user" && part.type === "text" && !seenUserMessages.has(msg.id)) {
            seenUserMessages.add(msg.id)
            const sessionID = msg.sessionID ?? currentSessionID
            if (sessionID) {
              await callHook("turn-start", {
                session_id: sessionID,
                transcript_path: `${transcriptDir}/${sessionID}.jsonl`,
                prompt: part.text ?? "",
                ...hookModelPayload(msg, currentSessionInfo),
              })
            }
          }
          break
        }

        case "session.status": {
          const props = (event as any).properties
          if (props?.status?.type !== "idle") break
          const sessionID = props?.sessionID
          if (!sessionID) break
          const transcriptPath = await writeTranscriptWithFallback(sessionID)
          await writeExportJSON(sessionID)
          callHookSync("turn-end", {
            session_id: sessionID,
            transcript_path: transcriptPath,
            ...hookModelPayload(latestSessionModelMetadata(sessionID)),
          })
          break
        }

        case "session.compacted": {
          const sessionID = (event as any).properties?.sessionID
          if (!sessionID) break
          await callHook("compaction", {
            session_id: sessionID,
            transcript_path: `${transcriptDir}/${sessionID}.jsonl`,
            ...hookModelPayload(latestSessionModelMetadata(sessionID)),
          })
          break
        }

        case "session.deleted": {
          const session = (event as any).properties?.info
          if (!session?.id) break
          const modelMetadata = latestSessionModelMetadata(session.id)
          // Write final transcript + export JSON before signaling session end
          if (messageStore.size > 0) {
            await writeTranscriptFromMemory(session.id)
            await writeExportJSON(session.id)
          }
          seenUserMessages.clear()
          messageStore.clear()
          partStore.clear()
          currentSessionID = null
          currentSessionInfo = null
          callHookSync("session-end", {
            session_id: session.id,
            transcript_path: `${transcriptDir}/${session.id}.jsonl`,
            ...hookModelPayload(modelMetadata),
          })
          break
        }
      }
    },
  }
}
"##;
