//! Text utility helpers.

use regex::Regex;
use std::sync::OnceLock;

/// Removes IDE/system context tags from prompt text.
///
pub fn strip_ide_context_tags(text: &str) -> String {
    static IDE_CONTEXT_TAG_RE: OnceLock<Regex> = OnceLock::new();
    static USER_QUERY_TAG_RE: OnceLock<Regex> = OnceLock::new();
    static SYSTEM_TAG_RES: OnceLock<Vec<Regex>> = OnceLock::new();

    let ide_context_tag_re = IDE_CONTEXT_TAG_RE.get_or_init(|| {
        Regex::new(r"(?s)<ide_[^>]*>.*?</ide_[^>]*>").expect("valid ide context regex")
    });
    let user_query_tag_re = USER_QUERY_TAG_RE
        .get_or_init(|| Regex::new(r"(?s)</?user_query>").expect("valid user query tag regex"));
    let system_tag_res = SYSTEM_TAG_RES.get_or_init(|| {
        [
            r"(?s)<local-command-caveat[^>]*>.*?</local-command-caveat>",
            r"(?s)<system-reminder[^>]*>.*?</system-reminder>",
            r"(?s)<command-name[^>]*>.*?</command-name>",
            r"(?s)<command-message[^>]*>.*?</command-message>",
            r"(?s)<command-args[^>]*>.*?</command-args>",
            r"(?s)<local-command-stdout[^>]*>.*?</local-command-stdout>",
        ]
        .iter()
        .map(|pattern| Regex::new(pattern).expect("valid system context regex"))
        .collect::<Vec<_>>()
    });

    let mut result = ide_context_tag_re.replace_all(text, "").to_string();
    result = user_query_tag_re.replace_all(&result, "").to_string();
    for re in system_tag_res {
        result = re.replace_all(&result, "").to_string();
    }

    result.trim().to_string()
}

#[allow(non_snake_case)]
pub fn StripIDEContextTags(text: &str) -> String {
    strip_ide_context_tags(text)
}

#[cfg(test)]
mod tests {
    use super::strip_ide_context_tags;

    #[test]
    fn test_strip_ide_context_tags() {
        let tests = [
            (
                "no IDE tags",
                "make the returned number red",
                "make the returned number red",
            ),
            (
                "ide_opened_file tag only",
                "<ide_opened_file>The user opened the file /path/to/file.md in the IDE. This may or may not be related to the current task.</ide_opened_file>",
                "",
            ),
            (
                "ide_opened_file with real prompt",
                "<ide_opened_file>The user opened the file /path/to/file.md in the IDE.</ide_opened_file>\n\nmake the returned number red",
                "make the returned number red",
            ),
            (
                "ide_selection tag",
                "<ide_selection file=\"/path/file.rs\" lines=\"10-20\">selected code here</ide_selection>\n\nrefactor this function",
                "refactor this function",
            ),
            (
                "multiline ide_selection",
                "<ide_selection>func main() {\n    fmt.Println(\"hello\")\n}</ide_selection>\n\noptimize this",
                "optimize this",
            ),
            (
                "multiple IDE tags",
                "<ide_opened_file>file.rs</ide_opened_file>\n\n<ide_selection>some code</ide_selection>\n\nplease fix the bug",
                "please fix the bug",
            ),
            (
                "unknown future ide tag",
                "<ide_cursor_position line=\"42\" col=\"10\">cursor info</ide_cursor_position>\n\nhelp me here",
                "help me here",
            ),
            (
                "preserves other XML-like content",
                "<user_note>important</user_note> and <system>info</system>",
                "<user_note>important</user_note> and <system>info</system>",
            ),
            ("empty string", "", ""),
            (
                "whitespace only after stripping",
                "<ide_opened_file>file.md</ide_opened_file>   \n\n   ",
                "",
            ),
            (
                "local-command-caveat tag",
                "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>my actual prompt",
                "my actual prompt",
            ),
            (
                "system-reminder tag",
                "<system-reminder>This is a system reminder.</system-reminder>\n\nactual user text",
                "actual user text",
            ),
            (
                "command-name tag",
                "<command-name>/release-notes</command-name>",
                "",
            ),
            (
                "multiple system tags",
                "<local-command-caveat>caveat text</local-command-caveat><command-name>/test</command-name><command-message>msg</command-message><command-args>args</command-args>real prompt here",
                "real prompt here",
            ),
            (
                "local-command-stdout tag",
                "<local-command-stdout>output from command</local-command-stdout>\n\nuser prompt",
                "user prompt",
            ),
            (
                "mixed IDE and system tags",
                "<ide_opened_file>file.rs</ide_opened_file><system-reminder>reminder</system-reminder>\n\nactual prompt",
                "actual prompt",
            ),
            (
                "user_query wrapper",
                "<user_query>actual prompt</user_query>",
                "actual prompt",
            ),
        ];

        for (name, input, want) in tests {
            let got = strip_ide_context_tags(input);
            assert_eq!(got, want, "{name}");
        }
    }
}
