use std::path::{Path, PathBuf};

use anyhow::{Result, anyhow};

use super::plugin::{BITLOOPS_CMD_PLACEHOLDER, PLUGIN_TEMPLATE};

pub const PLUGIN_FILE_NAME: &str = "bitloops.ts";
pub const PLUGIN_DIR_NAME: &str = "plugins";
pub const BITLOOPS_MARKER: &str = "Auto-generated by `bitloops init --agent opencode`";

pub fn get_plugin_path(repo_root: &Path) -> PathBuf {
    repo_root
        .join(".opencode")
        .join(PLUGIN_DIR_NAME)
        .join(PLUGIN_FILE_NAME)
}

pub fn render_plugin_template(local_dev: bool) -> Result<String> {
    if !PLUGIN_TEMPLATE.contains(BITLOOPS_CMD_PLACEHOLDER) {
        return Err(anyhow!(
            "plugin template missing BITLOOPS command placeholder"
        ));
    }

    let bitloops_cmd = if local_dev {
        "cargo run --"
    } else {
        "bitloops"
    };

    Ok(PLUGIN_TEMPLATE.replace(BITLOOPS_CMD_PLACEHOLDER, bitloops_cmd))
}
