steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/bitloops-rest:${_TAG_ID}', '.' ]
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/bitloops-rest:${_TAG_ID}']
images:
  - 'gcr.io/${_PROJECT_ID}/bitloops-rest:${_TAG_ID}'