version: "3"

services:
  nats: 
    container_name: nats
    image: nats:latest
    ports:
      - 4222:4222
    networks:
      - bitloops

  nats-ui:
    container_name: nats-ui
    image: sphqxe/nats-webui:latest
    ports: 
      - 8082:80
    networks:
      - bitloops

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - bitloops
  
  bitloops-rest:
    build: .
    container_name: bitloops-rest
    image: bitloops/bitloops-rest:latest
    environment:
      - PORT=8080
      - ENV=dev
      - BITLOOPS_ENGINE_EVENTS_TOPIC=test-bitloops-engine-events
      - SHA256_SALT=blabla
      - MONGO_URL_PREFIX=mongodb://
      - MONGO_URL_SUFFIX=mongodb:27017
      - NATS_IP=nats
      - NATS_PORT=4222
    ports:
      - 8080:8080
    depends_on:
      - nats
      - mongodb
    networks:
      - bitloops

networks:
  bitloops:
    driver: bridge