apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  nats_user: {{ .Values.nats_user | b64enc }}
  nats_password: {{ .Values.nats_password | b64enc }}
  encryption_key: {{ .Values.encryption_key | b64enc }}
  mongo_user: {{ .Values.mongo_user | b64enc }}
  mongo_password: {{ .Values.mongo_password | b64enc }}