apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: btls-rest-port
    protocol: TCP
  selector:
    app: {{ $.Release.Name }}