name: Develop QAT

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DUCKDB_DOWNLOAD_LIB: '1'

jobs:
  qat:
    name: QAT
    runs-on: self-hosted
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: . -> target
          shared-key: develop-qat
          cache-workspace-crates: true

      - name: Run QAT acceptance suites
        run: cargo qat
